### ISSUE TITLE
Failed to apply patch: 0004-fix-ipaddress-syntaxwarning.patch

### ISSUE THREAD

**Issue by cerk** [sudoforge/pkgbuilds#16] opened 2020-03-21 20:17 UTC
On arch linux, when I attempt to "makepkg -si" the google-cloud-sdk package, I get:

`==> Making package: google-cloud-sdk 285.0.1-1 (Sat 21 Mar 2020 03:54:54 PM EDT)`
`==> Checking runtime dependencies...`
`==> Checking buildtime dependencies...`
`==> Retrieving sources...`
`  -> Downloading google-cloud-sdk_285.0.1.orig.tar.gz...`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`100 56.6M  100 56.6M    0     0  13.9M      0  0:00:04  0:00:04 --:--:-- 13.9M`
`  -> Found google-cloud-sdk.sh`
`  -> Found 0001-fix-console-io-syntax-warning.patch`
`  -> Found 0002-set-python2-for-dev-appserver-py.patch`
`  -> Found 0003-set-python2-for-endpointscfg-py.patch`
`==> Validating source files with sha256sums...`
`    google-cloud-sdk_285.0.1.orig.tar.gz ... Passed`
`    google-cloud-sdk.sh ... Passed`
`    0001-fix-console-io-syntax-warning.patch ... Passed`
`    0002-set-python2-for-dev-appserver-py.patch ... Passed`
`    0003-set-python2-for-endpointscfg-py.patch ... Passed`
`==> Extracting sources...`
`  -> Extracting google-cloud-sdk_285.0.1.orig.tar.gz with bsdtar`
`==> Starting prepare()...`
`failed to apply patch: 0004-fix-ipaddress-syntaxwarning.patch`
`==> ERROR: A failure occurred in prepare().`
`    Aborting...`

There is no 0004-fix-ipaddress-syntaxwarning.patch file in the google-cloud-sdk directory. I must be doing something wrong but I don't know where to start. I've successfully made this package in the past, but I've started to have this issue in the last couple of weeks.

Any suggestions? Thank you for reading!

**Comment by sudoforge** [comment] 2020-03-21 20:44
Huh, that certainly is odd -- the [code that handles patching][0] doesn't specify any particular filename, instead preferring to dynamically apply all patch files. I chose this method specifically to avoid issues with adding/removing patches!

Since you're using `makepkg` directly, I think the likely issue here is that you haven't cleaned the `src/` directory from the last time you built, which would have been prior to https://github.com/sudoforge/pkgbuilds/commit/fc6cf9fb13258e87e6375292a5e41106aee8a878, which removed that particular patch file.

From `man makepkg`:

```
OPTIONS
       -c, --clean
           Clean up leftover work files and directories after a successful build.

       -C, --cleanbuild
           Remove the $srcdir before building the package.
```

Providing the `--cleanbuild` option should help get you moving now, and adding the `--clean` option to your future commands should help prevent this issue when building `google-cloud-sdk` and other packages.

[0]: https://github.com/sudoforge/pkgbuilds/blob/master/google-cloud-sdk/PKGBUILD#L36-L38

**Comment by sudoforge** [comment] 2020-03-21 20:44
Let me know if that helps!

**Comment by sudoforge** [comment] 2020-03-21 21:34
Here's a bulleted guide to reproducing this issue: 

* Clone this repository: `git clone https://github.com/sudoforge/pkgbuilds.git`
* Checkout the last revision with the patch file: `git checkout d56aa760e84b32d84286e0be563bf5d9a0266b8d`
* Move to the package directory: `cd google-cloud-sdk`
* Build the package (`-s` to install deps): `makepkg -s`
* Switch to any newer revision: `git checkout origin/master`
* Build the newer version: `makepkg -s`

This reproduces the error, as expected, because the `src/` directory is not clean and still contains the `0004-fix-ipaddress-syntaxwarning.patch` file. Using the `-C` or `--cleanbuild` flag cleans the `src/` directory before building the package, which avoids this issue.

It would perhaps be better to explicitly pass the appropriate patch filenames to the `patch` command, at the cost of maintenance ergonomics -- it would avoid issues like this, but ensuring that the build environment is clean isn't really the job of the `PKGBUILD`. I'm going to close this for now, but feel free to comment if the issue persists for you.

**Closed by sudoforge** 2020-03-21 21:34 UTC
Labels: pkg:google-cloud-sdk, state:confirmed, type:bug
