### ISSUE TITLE
google-cloud-sdk package files did not pass the validity check!

### ISSUE THREAD

**Issue by alejandrohall** [sudoforge/pkgbuilds#61] opened 2022-03-25 10:51 UTC
When trying to update the `google-cloud-sdk` package I'm getting the following error: 

```
:: (1/1) Parsing SRCINFO: google-cloud-sdk
==> Making package: google-cloud-sdk 378.0.0-1 (vie 25 mar 2022 11:47:10)
==> Retrieving sources...
  -> Found google-cloud-sdk_378.0.0.orig.tar.gz
  -> Found google-cloud-sdk.sh
  -> Found 0001-set-python2-for-dev-appserver-py.patch
  -> Found 0002-set-python2-for-endpointscfg-py.patch
  -> Found 0003-add-compdef-to-zsh-completion.patch
  -> Found 0004-collections-abc.patch
==> Validating source files with sha256sums...
    google-cloud-sdk_378.0.0.orig.tar.gz ... FAILED
    google-cloud-sdk.sh ... Passed
    0001-set-python2-for-dev-appserver-py.patch ... Passed
    0002-set-python2-for-endpointscfg-py.patch ... Passed
    0003-add-compdef-to-zsh-completion.patch ... Passed
    0004-collections-abc.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: google-cloud-sdk 
	 context: exit status 1 
	 

==> Making package: google-cloud-sdk 378.0.0-1 (vie 25 mar 2022 11:47:12)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found google-cloud-sdk_378.0.0.orig.tar.gz
  -> Found google-cloud-sdk.sh
  -> Found 0001-set-python2-for-dev-appserver-py.patch
  -> Found 0002-set-python2-for-endpointscfg-py.patch
  -> Found 0003-add-compdef-to-zsh-completion.patch
  -> Found 0004-collections-abc.patch
==> Validating source files with sha256sums...
    google-cloud-sdk_378.0.0.orig.tar.gz ... FAILED
    google-cloud-sdk.sh ... Passed
    0001-set-python2-for-dev-appserver-py.patch ... Passed
    0002-set-python2-for-endpointscfg-py.patch ... Passed
    0003-add-compdef-to-zsh-completion.patch ... Passed
    0004-collections-abc.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error making: google-cloud-sdk
```

**Comment by sudoforge** [comment] 2022-03-25 13:03
I am unable to recreate this on my personal machine, and the logs on my CI server show that this built successfully in a chroot.

As you can see, you failed downloading the archive:

```
 -> error downloading sources: google-cloud-sdk 
	 context: exit status 1 
```

Please clean your workspace, ensure you're using the latest commit, and build it again. If the issue persists, debug why you are unable to download the archive by attempting to download it manually:

```
➜ curl -Lo /tmp/google-cloud-sdk-378.0.0.tar.gz https://dl.google.com/dl/cloudsdk/release/downloads/for_packagers/linux/google-cloud-sdk_378.0.0.orig.tar.gz
```

> Pro tip: add `--verbose` to your `curl` call for more useful information.

I'm going to close this now because it is a non-issue, but I am happy to continue helping you debug your system via comments so that you can successfully build the package.

**Closed by sudoforge** 2022-03-25 13:03 UTC

**Comment by sudoforge** [comment] 2022-03-25 13:05
I should also note that this error message may be caused by whatever AUR helper you're using, if any. Be sure to build with `makepkg` or `makechrootpkg` (or use the useful thin wrapper utility, [`aurutils`](https://github.com/AladW/aurutils]).

**Comment by sudoforge** [comment] 2022-03-26 20:48
Hey @alejandrohall, were you able to successfully build the package?

**Comment by alejandrohall** [comment] 2022-03-28 12:42
Hi @sudoforge!

Sorry it was my fault, after cleaning the workspace I was able to install it correctly, it seems the package was in a inconsistent state. Thanks!
