### ISSUE TITLE
failed to apply patch: 0004-collections-abc.patch

### ISSUE THREAD

**Issue by chenghung** [sudoforge/pkgbuilds#53] opened 2021-12-15 12:56 UTC
I'm trying to install google-cloud-sdk_367.0.0
but build failed due to "failed to apply patch: 0004-collections-abc.patch"

**Comment by sudoforge** [comment] 2021-12-15 13:26
Can you confirm the version of the package that you are trying to install? There was an error in `google-cloud-sdk-367.0.0-1` that should be fixed in `-2` and `-3` (a pipeline tests building in a clean chroot before exporting to the AUR -- `-1` snuck by due to a caching issue)

**Comment by catwell** [comment] 2021-12-15 13:46
I have the same issue while installing 367.0.0-3.

**Comment by sudoforge** [comment] 2021-12-15 13:47
Duplicate of #51.

**Comment by sudoforge** [comment] 2021-12-15 13:47
@catwell I responded here before seeing other notifications; please check #51.

**Closed by sudoforge** 2021-12-15 13:47 UTC
Labels: state: duplicate
